// utils/complexityInfo.js

export const complexityInfo = {
  bubble: {
    name: "Bubble Sort",
    best: "O(n)",
    average: "O(n²)",
    worst: "O(n²)",
    space: "O(1)",
    stable: true,
    desc: "Repeatedly swaps adjacent elements if they are in the wrong order. Simple but slow on large data.",
  },
  selection: {
    name: "Selection Sort",
    best: "O(n²)",
    average: "O(n²)",
    worst: "O(n²)",
    space: "O(1)",
    stable: false,
    desc: "Finds the minimum element and places it at the beginning. Makes at most n-1 swaps.",
  },
  insertion: {
    name: "Insertion Sort",
    best: "O(n)",
    average: "O(n²)",
    worst: "O(n²)",
    space: "O(1)",
    stable: true,
    desc: "Builds a sorted array one item at a time, like sorting playing cards in your hand.",
  },
  merge: {
    name: "Merge Sort",
    best: "O(n log n)",
    average: "O(n log n)",
    worst: "O(n log n)",
    space: "O(n)",
    stable: true,
    desc: "Divides array into halves, sorts each half, then merges them. Consistent O(n log n) performance.",
  },
  quick: {
    name: "Quick Sort",
    best: "O(n log n)",
    average: "O(n log n)",
    worst: "O(n²)",
    space: "O(log n)",
    stable: false,
    desc: "Picks a pivot and partitions the array around it. Fastest in practice for most datasets.",
  },
  linear_search: {
    name: "Linear Search",
    best: "O(1)",
    average: "O(n)",
    worst: "O(n)",
    space: "O(1)",
    stable: true,
    desc: "Scans every element from left to right. Works on unsorted arrays but can be slow.",
  },
  binary_search: {
    name: "Binary Search",
    best: "O(1)",
    average: "O(log n)",
    worst: "O(log n)",
    space: "O(1)",
    stable: true,
    desc: "Repeatedly halves the search space. Requires a sorted array. Very efficient.",
  },
  singly_insert_head: {
    name: "Insert at Head",
    best: "O(1)",
    average: "O(1)",
    worst: "O(1)",
    space: "O(1)",
    stable: true,
    desc: "Creates a new node and points it to the current head. The new node becomes the new head.",
  },
  singly_traversal: {
    name: "LL Traversal",
    best: "O(n)",
    average: "O(n)",
    worst: "O(n)",
    space: "O(1)",
    stable: true,
    desc: "Visits each node starting from head, following next pointers until reaching NULL.",
  },
  singly_insert_tail: {
    name: "Insert at Tail",
    best: "O(n)",
    average: "O(n)",
    worst: "O(n)",
    space: "O(1)",
    stable: true,
    desc: "Traverses the entire list to find the last node, then links a new node to its next pointer.",
  },
  singly_insert_pos: {
    name: "Insert at Position",
    best: "O(1)",
    average: "O(n)",
    worst: "O(n)",
    space: "O(1)",
    stable: true,
    desc: "Walks to the node just before the target position, then splices the new node in between.",
  },
  singly_delete_head: {
    name: "Delete at Head",
    best: "O(1)",
    average: "O(1)",
    worst: "O(1)",
    space: "O(1)",
    stable: true,
    desc: "Moves head pointer to head→next and frees the old head node. Constant-time operation.",
  },
  singly_delete_tail: {
    name: "Delete at Tail",
    best: "O(n)",
    average: "O(n)",
    worst: "O(n)",
    space: "O(1)",
    stable: true,
    desc: "Traverses to the second-to-last node, sets its next to NULL, and frees the former tail.",
  },
  singly_search: {
    name: "LL Search",
    best: "O(1)",
    average: "O(n)",
    worst: "O(n)",
    space: "O(1)",
    stable: true,
    desc: "Scans nodes from HEAD one-by-one comparing values until the target is found or NULL is reached.",
  },
  linear: {
    name: "Linear Search",
    best: "O(1)",
    average: "O(n)",
    worst: "O(n)",
    space: "O(1)",
    stable: true,
    desc: "Scans every element from left to right.",
  },
  binary: {
    name: "Binary Search",
    best: "O(1)",
    average: "O(log n)",
    worst: "O(log n)",
    space: "O(1)",
    stable: true,
    desc: "Repeatedly halves the search space on a sorted array.",
  },
};
